### ISSUE TITLE
想问一下师傅达拉崩的溢出是试出来的吗

### ISSUE THREAD

**Issue by Imtinmin** [ustclug/hackergame2019-writeups#36]
`v = -1900000000000000000` 不等于64位溢出`-(2**64+1) =-18446744073709551617 `

**Comment by ertuil** [comment]
并不是，用 64位整型数溢出的任意一个都行。 （-19xxxxx 这个数是为了试验某些在正式题目中没有激活的特性而构造的，没有特殊意义）

**Comment by Imtinmin** [comment]
> 并不是，用 64位整型数溢出的任意一个都行。 （-19xxxxx 这个数是为了试验某些在正式题目中没有激活的特性而构造的，没有特殊意义）
> […](#)
> 在 2019年10月24日，11:49，tinmin ***@***.***> 写道： ﻿ v = -1900000000000000000 不等于64位溢出-(2**64+1) =-18446744073709551617 — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

emmm,还有就是为什么是负数溢出

**Comment by ertuil** [comment]
不一定 正数也可能溢出
